<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsTrimmable>true</IsTrimmable>
        <EnableAoTAnalyzer>true</EnableAoTAnalyzer>
        <PublishTrimmed>true</PublishTrimmed>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>ModelsDotDevSharp</PackageId>
        <Title>ModelsDotDevSharp</Title>
        <Authors>Alastair Lundy</Authors>
        <Copyright>Copyright (c) Alastair Lundy 2026</Copyright>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/alastairlundy/ModelsDotDevSharp</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageVersion>0.1.0</PackageVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Description>A .NET client wrapper for the models.dev API.</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <Product>ModelsDotDevSharp</Product>
        <PackageTags>models.dev, LLMs, AI, models-dot-dev, models</PackageTags>
        <PackageReleaseNotes>Initial Release</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Options" />

      <Content Include="..\..\README.md" Pack="true">
        <PackagePath>README.md</PackagePath>
        </Content>
    </ItemGroup>

</Project>
